# Generated by Django 3.2.7 on 2021-09-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='null', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
